# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/svg/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.novoRegistro = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/svg/add_row.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.novoRegistro.setIcon(icon1)
        self.novoRegistro.setObjectName("novoRegistro")
        self.horizontalLayout.addWidget(self.novoRegistro)
        self.editarRegistro = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/svg/edit_image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editarRegistro.setIcon(icon2)
        self.editarRegistro.setObjectName("editarRegistro")
        self.horizontalLayout.addWidget(self.editarRegistro)
        self.gerarRelatorio = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/svg/neutral_trading.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gerarRelatorio.setIcon(icon3)
        self.gerarRelatorio.setObjectName("gerarRelatorio")
        self.horizontalLayout.addWidget(self.gerarRelatorio)
        self.removerRegistro = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/img/svg/remove_image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removerRegistro.setIcon(icon4)
        self.removerRegistro.setObjectName("removerRegistro")
        self.horizontalLayout.addWidget(self.removerRegistro)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.registrosMensais = QtWidgets.QTableWidget(self.centralwidget)
        self.registrosMensais.setObjectName("registrosMensais")
        self.registrosMensais.setColumnCount(4)
        self.registrosMensais.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.registrosMensais.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrosMensais.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrosMensais.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrosMensais.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.registrosMensais)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMoradores = QtWidgets.QMenu(self.menubar)
        self.menuMoradores.setObjectName("menuMoradores")
        self.menuTipoContas = QtWidgets.QMenu(self.menubar)
        self.menuTipoContas.setObjectName("menuTipoContas")
        MainWindow.setMenuBar(self.menubar)
        self.listarMoradores = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/svg/list.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listarMoradores.setIcon(icon5)
        self.listarMoradores.setObjectName("listarMoradores")
        self.addMorador = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/img/svg/add_database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addMorador.setIcon(icon6)
        self.addMorador.setObjectName("addMorador")
        self.listarTipoConta = QtWidgets.QAction(MainWindow)
        self.listarTipoConta.setIcon(icon5)
        self.listarTipoConta.setObjectName("listarTipoConta")
        self.addTipoConta = QtWidgets.QAction(MainWindow)
        self.addTipoConta.setIcon(icon6)
        self.addTipoConta.setObjectName("addTipoConta")
        self.menuMoradores.addAction(self.addMorador)
        self.menuMoradores.addAction(self.listarMoradores)
        self.menuTipoContas.addAction(self.addTipoConta)
        self.menuTipoContas.addAction(self.listarTipoConta)
        self.menubar.addAction(self.menuMoradores.menuAction())
        self.menubar.addAction(self.menuTipoContas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Divisor de Contas"))
        self.novoRegistro.setText(_translate("MainWindow", "Novo Registro Mensal"))
        self.editarRegistro.setText(_translate("MainWindow", "Editar"))
        self.gerarRelatorio.setText(_translate("MainWindow", "Gerar Relatório"))
        self.removerRegistro.setText(_translate("MainWindow", "Remover"))
        item = self.registrosMensais.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.registrosMensais.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mês / Ano"))
        item = self.registrosMensais.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total"))
        item = self.registrosMensais.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total por Pessoa"))
        self.menuMoradores.setTitle(_translate("MainWindow", "Moradores"))
        self.menuTipoContas.setTitle(_translate("MainWindow", "Tipos de Contas"))
        self.listarMoradores.setText(_translate("MainWindow", "Listar"))
        self.addMorador.setText(_translate("MainWindow", "Adicionar"))
        self.listarTipoConta.setText(_translate("MainWindow", "Listar"))
        self.addTipoConta.setText(_translate("MainWindow", "Adicionar"))


from . import ImageResources
